### PR TITLE
doc(platforms) : Add Kaggle to supported platforms

### PR DESCRIPTION
**Pull request by adriens**
:bulb:  [Kaggle](https://www.kaggle.com/) could be added to supported platform

### CODE REVIEW

**Comment by mwouts** [comment]
Hey @adriens , oh nice to learn that ITables works on Kaggle too! Do you think you could add a screenshot at [docs/supported_editors.md](https://github.com/mwouts/itables/blob/main/docs/supported_editors.md) too? Thanks!

**Comment by adriens** [comment]
Sure, sure, I will I will very probably add it to my stack. 
Hopefully before next week : is the timeline ok for you ?

**Comment by mwouts** [comment]
Oh yes sure, no hurry at all! Thanks!

**Comment by adriens** [comment]
https://www.kaggle.com/code/adriensales/endoflife-date-database-for-dummies#%F0%9F%8F%B7%EF%B8%8F-Discover-tags

image

**Comment by mwouts** [comment]
Thank you @adriens for this! In the end I have added a simple mention of Kaggle in the readme while working on the streamlit documentation #277

**Pull request closed without merging**
