### PR TITLE
WIP Custom datatables requirements

### LINKED ISSUE #50: Add support for the datatables.net extensions like e.g. "buttons"
Can we add support for some extensions like buttons? See #18 for a first attempt.

### PR DESCRIPTION
**Pull request by mwouts**
With this PR I'd like to allow custom requirements for datatables, and let people use extensions like "search highlight" or "buttons".

Closes #50 

@qqdaiyu55 I don't think this is working properly at the moment, do you think you could help me fix the implementation and the examples ? Thanks !

### CODE REVIEW

**Comment by qqdaiyu55** [comment]
@mwouts hi, could u please describe the issue you met?
I'm pretty busy today, I can take a look in next few days

**Comment by mwouts** [comment]
Hello @qqdaiyu55 , sorry I come back to you only now.

I've done a bit more of testing, and this is what I find:
- this PR works well in Jupyter Book (i.e. when require is available)
- but in Jupyter Lab, some tables remain loading for ever, like in this screenshot:
image
- in addition, I have not been able yet to make the highlight example work in neither context (below in Jupyter book):
image

Do you think you can help me on these issues? Thanks!

**Comment by qqdaiyu55** [comment]
@mwouts Sure, I'll take a look. Could you please open the console in developer tool and share the error log?

**Comment by mwouts** [comment]
Thank you @qqdaiyu55 ! 

Below are some of the logs
1. In the version of `datatables_plugin.md` rendered with Jupyter Book (sorry this is a bit more complex than the standalone highlight example, because it has the buttons example first), I see errors about `$`: 
image
2. In Jupyter notebook (skipping the button example), the table does not load and I see these errors:
image
image
3. In Jupyter Lab (again, skipping the button example), the table is shown but the highlight does not work. I see an error but I don't think it is related:
image

**Comment by qqdaiyu55** [comment]
Sry for late reply, I'm quite busy these days.
I just test it with jupyter lab/notebook, it seems work well. Could you please share the notebook or code snippet which you find the problem?

image

**Comment by qqdaiyu55** [comment]
The screenshot you shared, these two errors, one in `doctool.js`, and the other in `sphinx`. None of them is related to your `itables` pkg.
image

**Comment by mwouts** [comment]
Just to mention that there might be some overlap between the work on the offline mode at #74 and this PR.

More specifically, the `addScript` function from @qqdaiyu55 's [comment](https://github.com/mwouts/itables/issues/63#issuecomment-1077185088)
```javascript
function addScript(src) {
                return new Promise((resolve, reject) => {
                    var script = document.createElement('script');
                    script.onload = resolve;
                    script.onerror = reject;
                    script.src = src;
                    document.head.appendChild(script);
                });
            }
```
might be used to load the `datatables` and `jquery` libraries from either the static folder or from a CDN at #74 - or conversely, if we find a more canonical way to load the libraries dynamically in Jupyter Lab then we might not need this `addScript` function...

**Comment by mwouts** [comment]
Superseded by #235

**Pull request closed without merging**
