### PR TITLE
Fix itables in Jupyter Lab

### LINKED ISSUE #3: Fix itables on Jupyter Lab
In Jupyter lab, importing `itables` yields an error: _Javascript Error: require is not defined_.

### PR DESCRIPTION
**Pull request by mwouts**
Fixes #3 

@fcollonval, is this a correct port of [your suggested fix](https://github.com/mwouts/itables/issues/3#issuecomment-688330386)?

At least that seems to work! I have tested it with 
```sh
pip install git+https://github.com/mwouts/itables.git@fix_itables_in_jlab
```
and the result is this:
image

### CODE REVIEW

**Comment by mwouts** [comment]
Is this possible that this works with Jupyter Lab 2.2.9 but not Jupyter Lab 3 or 4? I can't get this to work on Binder:
image

**Comment by mwouts** [comment]
Oh I think I see the problem... I can't use `require.config` to load `require`... But then I have no idea then on how to load `require` :laughing:

**Comment by fcollonval** [comment]
I would say that you can still use the trick of displaying HTML `script` tag to load `require`. But you will need to wait for it to be available before loading the Javascript using it. But a better (and more secure way) would be to use an iframe [like in that example for d3](https://discourse.jupyter.org/t/d3-in-jupyterlab/11367/4).

**Comment by mwouts** [comment]
> But a better (and more secure way) would be to use an iframe like in that example for d3.

Thanks @fcollonval. Yes that is an interesting suggestion! For now I think I'm just going to include the code snippet in the documentation, and next year I'll try the suggested approach.

**Pull request closed without merging**
